CExA-project/ddc

- include/ddc/chunk.hpp
- include/ddc/chunk_span.hpp
> Function call operators missing in Chunk/ChunkSpan

- include/ddc/chunk.hpp
- include/ddc/chunk_span.hpp
* use mcoords for multiple single dim coords/ mcoord for single multi-dim,
* support dims in different order
* improved validity checks
> Improved Chunk op()

- include/ddc/is_uniform_domain_v
- tests/uniform_discretization.cpp
- tests/uniform_domain.cpp
* use the correct dim name,
* add missing include
> Two minor fixes in tests

- docs/first_steps.md
- docs/heat_equation.md
- examples/.clang-format
- examples/heat_equation.cpp
This is mostly here to discuss the changes, this should be split in multiple PRs
> Example improvements

- include/ddc/detail/macros.hpp
- include/ddc/discrete_space.hpp
- include/ddc/experimental/single_discretization.hpp
- include/ddc/non_uniform_point_sampling.hpp
- include/ddc/uniform_point_sampling.hpp
@tpadioleau : How can I test that easily with an nvcc & hip compiler, could we add at least nvcc to our test infra?
> Use a single location for local space definition

- include/ddc/detail/kokkos.hpp
.data_handle() was called on a Kokkos::view
> fix data_handle on a kokkos::view

- benchmarks/splines.cpp
- include/ddc/kernels/splines/matrix_sparse.hpp
Re-tune splines to optimize performance for Release mode
> Splines tuning cpu

- examples/heat_equation.cpp
Some comments were added based on answers from Thomas and two variable names were changed for clarity in the heat equation example.
> Additional comments and changed variable names in heat equation example

- include/ddc/kernels/splines/knots_as_interpolation_points.hpp
> Splines update knots_as_interpolation_points

- benchmarks/splines_plot.py
> bandwidth -> throughput in benchmark

- examples/heat_equation_spectral.cpp
- include/ddc/kernels/fft.hpp
- tests/fft.cpp
> [FFT] init_fourier_space returns PeriodicSampling

- CMakeLists.txt
> cuFFT_AVAIL if Kokkos_ENABLE_CUDA=ON

- include/ddc/kernels/splines/matrix_sparse.hpp
After Gysela meeting discussion, we keep bicgstab on GPU
> Use gmres only with OMP

- include/ddc/kernels/splines/bsplines_non_uniform.hpp
- include/ddc/kernels/splines/bsplines_uniform.hpp
> Use kokkos_swap

- include/ddc/kernels/splines/spline_builder_2d.hpp
> [Splines] Fixes 402

- include/ddc/kernels/splines/matrix_sparse.hpp
> Ginkgo throw error if not converged

- include/ddc/kernels/splines/bsplines_non_uniform.hpp
- include/ddc/kernels/splines/bsplines_uniform.hpp
- include/ddc/non_uniform_point_sampling.hpp
- include/ddc/periodic_sampling.hpp
- include/ddc/uniform_point_sampling.hpp
Hide base classes of dimensions and internal dimensions.
> Hide base classes of dimensions

- include/ddc/kernels/splines/bsplines_non_uniform.hpp
- include/ddc/kernels/splines/bsplines_uniform.hpp
- include/ddc/kernels/splines/spline_builder.hpp
> [Splines] Remove is_radial

- include/ddc/discrete_element.hpp
- tests/discrete_element.cpp
> fix typo in DiscreteElement::operator--

- include/ddc/kernels/splines/bsplines_non_uniform.hpp
- include/ddc/kernels/splines/bsplines_uniform.hpp
- include/ddc/kernels/splines/greville_interpolation_points.hpp
> Align UniformBSplines API to NonUniformBSplines API

- CMakeLists.txt
https://gitlab.maisondelasimulation.fr/gysela-developpers/gyselalibxx/-/merge_requests/531#note_57616
> LAPACKE cmake workaround

- include/ddc/kernels/splines/splines_linear_problem_maker.hpp
- Privilegie `PDSTridiag` or `PDSBand` block, even if band is width.
> Minor optimizations in splines linear problem maker

- include/ddc/kernels/splines/bsplines_non_uniform.hpp
- include/ddc/kernels/splines/bsplines_uniform.hpp
- include/ddc/kernels/splines/constant_extrapolation_rule.hpp
- include/ddc/kernels/splines/deriv.hpp
- include/ddc/kernels/splines/greville_interpolation_points.hpp
- include/ddc/kernels/splines/knots_as_interpolation_points.hpp
- include/ddc/kernels/splines/spline_builder.hpp
- include/ddc/kernels/splines/spline_builder_2d.hpp
- include/ddc/kernels/splines/spline_evaluator.hpp
- include/ddc/kernels/splines/spline_evaluator_2d.hpp
> Tag -> CDim in splines

- include/ddc/kernels/splines/splines_linear_problem_2x2_blocks.hpp
- include/ddc/kernels/splines/splines_linear_problem_band.hpp
- include/ddc/kernels/splines/splines_linear_problem_dense.hpp
- include/ddc/kernels/splines/splines_linear_problem_pds_band.hpp
- include/ddc/kernels/splines/splines_linear_problem_pds_tridiag.hpp
- include/ddc/kernels/splines/splines_linear_problem_sparse.hpp
> Add const qualifiers on multi-rhs in SplinesLinearProblem childs

- examples/characteristics_advection.cpp
> Use alias GrevillePoints in characteristics_advection

- benchmarks/splines.cpp
- benchmarks/splines_plot.py
- include/ddc/kernels/splines/spline_builder.hpp
- include/ddc/kernels/splines/spline_builder_2d.hpp
- include/ddc/kernels/splines/splines_linear_problem_maker.hpp
- include/ddc/kernels/splines/splines_linear_problem_sparse.hpp
> Typo preconditioner

- benchmarks/splines.cpp
> Coord<X> in benchmark

- include/ddc/kernels/splines/greville_interpolation_points.hpp
- include/ddc/kernels/splines/knots_as_interpolation_points.hpp
- include/ddc/kernels/splines/spline_builder.hpp
- include/ddc/kernels/splines/spline_builder_2d.hpp
- include/ddc/kernels/splines/spline_evaluator.hpp
- include/ddc/kernels/splines/spline_evaluator_2d.hpp
> Left/Right -> Lower/Upper

- include/ddc/kernels/splines/bsplines_non_uniform.hpp
- include/ddc/kernels/splines/bsplines_uniform.hpp
- tests/splines/CMakeLists.txt
- tests/splines/bsplines.cpp
> Fix the evaluation of bsplines infinitesimally close to the boundary

- CMakeLists.txt
- install_test/CMakeLists.txt
I am thinking of using SameMinorVersion compatibility for major version 0
> Add missing DDCConfigVersion

- include/ddc/discrete_domain.hpp
> cartesian_prod empty specialization

- include/ddc/discrete_element.hpp
- include/ddc/discrete_vector.hpp
APIs seem already well aligned
> Change a condition to select a ctor of DiscreteElement, add missing value_type for DiscreteVector

- tests/splines/batched_2d_spline_builder.cpp
- tests/splines/batched_spline_builder.cpp
- tests/splines/extrapolation_rule.cpp
- replace `DDim<A, B, C>` by its definition when possible
> Simplify notations in splines tests

- tests/splines/extrapolation_rule.cpp
@EmilyBourne do you mind reviewing ?
> Rework to avoid if/else identical branches

- include/ddc/kernels/splines/splines_linear_problem_2x2_blocks.hpp
- include/ddc/kernels/splines/splines_linear_problem_band.hpp
- include/ddc/kernels/splines/splines_linear_problem_dense.hpp
- include/ddc/kernels/splines/splines_linear_problem_pds_band.hpp
- include/ddc/kernels/splines/splines_linear_problem_pds_tridiag.hpp
- tests/splines/splines_linear_problem.cpp
see https://github.com/kokkos/kokkos/commit/b027fc25977f0e879c43febe1d884585fe8c1db0
> Remove deprecated usage of public member variables of DualView

- include/ddc/ddc.hpp
- include/ddc/detail/dual_discretization.hpp
- include/ddc/discrete_space.hpp
> Refactor global variables implementation

- include/ddc/kokkos_allocator.hpp
In practice Kokkos guarantees more than what si stated in the documentation.
> Ensure the requested alignment is not too large
