include/ddc/detail/tagged_vector.hpp

it's nice to be able to use `{vx,vy}` where a `vxy` is expected and I don't see any danger with it

Make some ctors implicit

---

.github/workflows/tests.yml
include/ddc/discrete_space.hpp
include/ddc/dual_discretization.hpp
include/ddc/scope_guard.hpp

The idea is to keep record of allocations using type erasure when necessary. All deallocations happen at the destruction of the ddc scope guard, before the destruction of the Kokkos scope guard.

Implement a store to keep track of dynamic allocations

---

include/ddc/discrete_space.hpp
include/ddc/dual_discretization.hpp

Use a proxy class to store non-trivially constructible objects in the constant memory space

Avoid extra memory allocation

---

include/ddc/uniform_point_sampling.hpp

`uniform_point_sampling.hpp` is raising the following warning:
```
/home/emily/Code/VOICE/voicexx/vendor/ddc/include/ddc/uniform_point_sampling.hpp: In static member function ‘static std::tuple<ddc::UniformPointSampling<CDim>::Impl<Kokkos::HostSpace>, ddc::DiscreteDomain<ddc::UniformPointSampling<CDim> >, ddc::DiscreteDomain<ddc::UniformPointSampling<CDim> >, ddc::DiscreteDomain<ddc::UniformPointSampling<CDim> >, ddc::DiscreteDomain<ddc::UniformPointSampling<CDim> > > ddc::UniformPointSampling<CDim>::init_ghosted(ddc::UniformPointSampling<CDim>::continuous_element_type, ddc::UniformPointSampling<CDim>::continuous_element_type, ddc::UniformPointSampling<CDim>::discrete_vector_type, ddc::UniformPointSampling<CDim>::discrete_vector_type, …
```

Remove line raising unused warning

---

CMakeLists.txt
docker/doxygen/Dockerfile
docker/latest/Dockerfile
docker/oldest/Dockerfile
include/ddc/misc/ginkgo_executors.hpp

Changes:
- remove deprecated calls of Ginkgo 1.7.0

Update Ginkgo dependency to version 1.7.0

---

include/ddc/kernels/splines/spline_builder.hpp
include/ddc/kernels/splines/spline_builder_2d.hpp
include/ddc/kernels/splines/spline_evaluator.hpp
include/ddc/kernels/splines/spline_evaluator_2d.hpp
tests/splines/batched_2d_spline_builder.cpp
tests/splines/batched_spline_builder.cpp
tests/splines/extrapolation_rule.cpp
tests/splines/matrix.cpp
tests/splines/periodicity_spline_builder.cpp

- Template spline_builder_2d with solver
- Single-coordinate SplineEvaluator::operator() are based on 1d spline coefs (like evals)
- Change types in loops to avoid warnings

Splines minor fixes

---

include/ddc/kernels/splines/bsplines_uniform.hpp

In the uniform bsplines there is a function with the following prototype:
```cpp
template <class Tag, std::size_t D>
template <class MemorySpace>
template <std::size_t Size>
KOKKOS_INLINE_FUNCTION ddc::DiscreteElement<UniformBSplines<Tag, D>> UniformBSplines<Tag, D>::
Impl<MemorySpace>::eval_basis(
std::array<double, Size>& values,
ddc::Coordinate<Tag> const& x,
std::size_t const deg) const
```
There is an assertion about the size:
```cpp
assert(values.size() == deg + 1);
```
followed by a loop which modifies `values`:
```cpp
for (std::size_t j = 1; j < deg + 1; ++j) {
```
When optimisations are turned on the compiler may try to unroll this loop. As `deg + 1` is not a `constexpr` the loop is unrolled beyond what is necessary leading to warnings such as:
``` …
```

Fix excessive loop unrolling

---

include/ddc/kernels/splines/spline_evaluator.hpp
include/ddc/kernels/splines/spline_evaluator_2d.hpp

Homogenise names of extrapolation rules in `SplineEvaluator` and `SplineEvaluator2D`. Add public type identifiers for the extrapolation rule types and getters for the operators. Fixes #345

Expose ExtrapolationRules from SplineEvaluator

---

benchmarks/splines.cpp
examples/characteristics_advection.cpp
include/ddc/kernels/splines/spline_evaluator.hpp
include/ddc/kernels/splines/spline_evaluator_2d.hpp
tests/splines/batched_2d_spline_builder.cpp
tests/splines/batched_spline_builder.cpp
tests/splines/extrapolation_rule.cpp
tests/splines/non_periodic_spline_builder.cpp
tests/splines/periodic_spline_builder.cpp
tests/splines/periodicity_spline_builder.cpp

Decouple `SplineEvaluator` from spline domain to prevent potential segmentation faults when using a smaller batch domain or unexpectedly non-updated values when using a larger batch domain. Fixes #344

Decouple SplineEvaluator from domain

---

include/ddc/kernels/splines/constant_extrapolation_rule.hpp
include/ddc/kernels/splines/greville_interpolation_points.hpp
include/ddc/kernels/splines/spline_builder.hpp
include/ddc/kernels/splines/spline_builder_2d.hpp
include/ddc/kernels/splines/spline_evaluator_2d.hpp

Update spline kernels with improvements from SLL. For most files this only concerns documentation. However for `include/ddc/kernels/splines/greville_interpolation_points.hpp` there is a bug fix. The periodic point *must* be calcucated in the helper class in order to be able to evaluate the length of the domain.

Update spline kernels with improvements from SLL

---

include/ddc/kernels/splines/spline_evaluator_2d.hpp
tests/splines/extrapolation_rule.cpp

When using `SplineEvaluator2D` to evaluate a point (r,theta) outside the domain, the periodic conditions should be applied before the non-periodic conditions. This is important because in a periodic direction no points are truly outside the domain. They should therefore be relocated before calling something like `ConstantExtrapolationRule`.

Fix out of bounds periodic evaluation

---

include/ddc/kernels/splines/matrix_sparse.hpp

Following https://github.com/ginkgo-project/ginkgo/issues/1563#issuecomment-2024928079
Using Gmres avoid the problem. Stopping criteria needed to be relaxed to make all tests pass (2D splines were slightly failing which means 1e-19 leads to some kind of non-convergency. It is also in accord with recommandation here: https://github.com/ginkgo-project/ginkgo/issues/1563#issuecomment-1986031356)
OMP preconditionner parameter (Jacobi-block-size) is set to 1 again because of Ginkgo recommandation, and because we do not observe huge performance improvement on splines with preconditionner (~18% at most in old benchmarks).
BiCGStab should be recovered once the problem has been fixed from Ginkgo side.
It solves all problems we had due to this issue (in Gysela or DDC)

Workaround ginkgo omp problem (use Gmres)

---

include/ddc/kernels/splines/bsplines_non_uniform.hpp
include/ddc/kernels/splines/bsplines_uniform.hpp

`rank()` is a residual from an old functionning of DDC.

[Splines] remove rank()

---

include/ddc/kernels/splines/spline_builder.hpp
include/ddc/kernels/splines/spline_evaluator.hpp
include/ddc/kernels/splines/spline_evaluator_2d.hpp

spline_dim_type is unused in ddc and gysela.
If we have no practical use case I think we should remove it

Remove spline_dim_type

---

include/ddc/discrete_domain.hpp
tests/discrete_domain.cpp

Add a function to initialise a `DiscreteDomain` from a `DiscreteDomain` with a different ordering. Fixes #419

Allow the reordering of a DiscreteDomain

---

include/ddc/kernels/splines/spline_builder.hpp

`compute_offset` has no reason to be public

[Splines] Privatize compute_offset

---

include/ddc/kernels/splines/spline_boundary_conditions.hpp
include/ddc/kernels/splines/spline_builder.hpp

`ddc::BoundCond::NATURAL` is used nowhere, not tested and even not fully implement.
`n_user_input()` is also removed because the returned value was different from `n_boundary_equations()`

[Splines] Remove NATURAL boundary condition

---

include/ddc/kernels/splines/matrix.hpp
include/ddc/kernels/splines/matrix_maker.hpp
include/ddc/kernels/splines/matrix_sparse.hpp

I propose to not document those classes extensively as the API is going to change (at least, not document extensively the methods which are subject to those changes.

Matrix classes doc

---

benchmarks/splines.cpp
include/ddc/kernels/splines/bsplines_non_uniform.hpp
include/ddc/kernels/splines/bsplines_uniform.hpp
include/ddc/kernels/splines/greville_interpolation_points.hpp
include/ddc/kernels/splines/knots_as_interpolation_points.hpp

Use DDC concepts for B-spline knots.
- Rename `mesh_type` -> `knot_mesh_type` and make it public
- Remove `get_knot` function
- Modify `get_first_support_knot` and `get_last_support_knot` to return `DiscreteElement`s
- Remove arithmetic on `uid` objects

Use DDC concepts for B-spline knots

---

include/ddc/kernels/splines/bsplines_non_uniform.hpp
include/ddc/kernels/splines/bsplines_uniform.hpp
include/ddc/kernels/splines/spline_builder.hpp
include/ddc/kernels/splines/spline_builder_2d.hpp

- Align bsplines move-constructor docstrings on SplineBuilder one.
- Add missing dots.

Splines doc minor corrections

---

include/ddc/kernels/splines/spline_builder.hpp

- `spline_tr` was allocating too much rows (they were unused).
- Rely on ddc::parallel_fill and Kokkos::deep_copy to fill `splines` with `vals`

SplineBuilder minor optimization

---

include/ddc/kernels/splines/bsplines_non_uniform.hpp
include/ddc/kernels/splines/bsplines_uniform.hpp

Bsplines relax float asserts

---

examples/characteristics_advection.cpp

Allow to run example in non-periodic setup, with GREVILLE and NullExtrapolation.

Characteristics advection non-periodic

---

tests/splines/CMakeLists.txt
tests/splines/splines_linear_problem.cpp

Rename Matrix tests

---

include/ddc/kernels/splines/spline_builder.hpp
include/ddc/kernels/splines/splines_linear_problem.hpp
include/ddc/kernels/splines/splines_linear_problem_3x3_blocks.hpp
tests/splines/matrix.cpp

Avoid deep_copies of `b_center`
Profiling on reference case with GREVILLE shows a 45% perf improvement (with KK on GPU) with this patch.
The downside of it is the SplinesLinearProblem3x3Blocks requires an allocation of `b` with `top_size` additional rows (which makes the SplineBuilder a bit more complex it already is)

Optimize 3x3 blocks

---

tests/splines/batched_2d_spline_builder.cpp
tests/splines/batched_spline_builder.cpp
tests/splines/extrapolation_rule.cpp
tests/splines/non_periodic_spline_builder.cpp
tests/splines/periodicity_spline_builder.cpp

Closes #231 
`1` suffixing -> `_1d` suffixing
`_cpu` -> `_host`
`Sderiv`-> `derivs`
Rely on `ddc::create_mirror_view_and_copy` for CPU<->GPU deepcopies.

Readability improvement in splines tests

---

include/ddc/create_mirror.hpp

- Fix asynchronous behavior using `parallel_deepcopy(dst, src)`.
- Allow to pass a memory space.
- Improve documentation.

Improve `create_mirror[_view][_and_copy]` functions

---

include/ddc/discrete_domain.hpp
include/ddc/kernels/splines/spline_builder.hpp
include/ddc/kernels/splines/spline_builder_2d.hpp
include/ddc/kernels/splines/spline_evaluator.hpp
include/ddc/kernels/splines/spline_evaluator_2d.hpp
tests/discrete_domain.cpp

Types associated to `remove_dims_of` and `replace_dims_of`.
Necessary for a Gysela MR.

remove_dims_of_t and replace_dims_of_t

---

include/ddc/kernels/splines/splines_linear_problem_sparse.hpp

Limits memory footprint
Also improves performance:

Buffer in SplinesLinearSolverSparse

---

include/ddc/kernels/fft.hpp
include/ddc/kernels/splines/spline_boundary_conditions.hpp
include/ddc/kernels/splines/spline_builder.hpp
tests/fft/fft.cpp

- turn switches into `if/else` blocks
- remove duplicate switches in `compute_block_sizes_*` functions

Remove switches and catch bad values

---

include/ddc/kernels/fft.hpp

The "full" normalization can be simplified by defining a 1d normalization factor that would also avoid duplication

Simplify fft full normalization

---

.github/workflows/tests.yml
CMakeLists.txt
cmake/DDCConfig.cmake.in
install_test/CMakeLists.txt
install_test/main.cpp

It seems to be working but could be further improved in future PR.
- The headers related to fft, splines and the PDI wrapper of DDC are being installed whatever the values of the cmake options. I think it could improved with some reorganization.
- Cmake targets about the fft and splines are missing.
- We should look at cmake components. As long as the user can adapt it looks ok
```cmake
find_package(DDC REQUIRED)
add_executable(main main.cpp)
target_link_libraries(main PRIVATE DDC::DDC)
if(DDC_BUILD_PDI_WRAPPER)
target_link_libraries(main PRIVATE DDC::PDI_Wrapper)
endif()
```
but as soon as a user requires an option this looks bad
```cmake
find_package(DDC REQUIRED)
if(NOT DDC_BUILD_KERNELS_FFT)
message(FATAL_ERROR "Expecting DDC_BUILD_KERNELS_FFT=ON")
endif()
```
- DDC lacks a header …

Add missing dependencies on installed DDC

---

.github/workflows/tests.yml
CMakeLists.txt
include/ddc/chunk.hpp
include/ddc/chunk_span.hpp
include/ddc/detail/kokkos.hpp
include/ddc/kernels/splines/bsplines_non_uniform.hpp
include/ddc/kernels/splines/bsplines_uniform.hpp
include/ddc/kernels/splines/spline_builder.hpp
tests/splines/bsplines.cpp

DDC should not force dependent projects to use `MDSPAN_USE_PAREN_OPERATOR=1`. Moreover this variable only makes sense in the Kokkos implementation of mdspan. A compiler provided implementation will likely not provide this variable neither the function call operator, see [cppref](https://en.cppreference.com/w/cpp/container/mdspan).
In this PR, DDC adapts to the mdspan implementation, defaulting on using the bracket operator.
Note that there is a bug with llvm 15/16, see the reproducer on [godbolt](https://godbolt.org/#g:!((g:!((g:!((h:codeEditor,i:(filename:'1',fontScale:13,fontUsePx:'0',j:1,lang:c%2B%2B,selection:(endColumn:1,endLineNumber:20,positionColumn:1,positionLineNumber:20,selectionStartColumn:1,selectionStartLineNumber:20,startColumn:1,startLineNumber:20),source:'%23include+%3Carr …

Remove definition MDSPAN_USE_PAREN_OPERATOR=1 from DDC target

---

CMakeLists.txt
benchmarks/CMakeLists.txt
cmake/DDCConfig.cmake.in
examples/CMakeLists.txt
install_test/CMakeLists.txt
tests/CMakeLists.txt
tests/discrete_space/CMakeLists.txt
tests/fft/CMakeLists.txt
tests/splines/CMakeLists.txt

Current public targets:
- `DDC::core` contains the core part of DDC
- `DDC::pdi` and `DDC::PDI_Wrapper` (deprecated) contain the PDI extension
- `DDC::fft` contains the FFT extension
- `DDC::splines` contains the Splines extension
- `DDC::DDC` contains all

Add ddc, fft, pdi and splines targets

---

include/ddc/kernels/splines/spline_evaluator.hpp
include/ddc/kernels/splines/spline_evaluator_2d.hpp

Add a batched `operator()` and derivative operators to `SplineEvaluator` and `SplineEvaluator2D` without the coordinates argument. Fixes #684

Add a batched operator() to SplineEvaluator without the coordinates argument

---

include/ddc/kernels/splines/bsplines_uniform.hpp
include/ddc/kernels/splines/spline_builder.hpp
tests/splines/CMakeLists.txt
tests/splines/spline_builder.cpp

Add functions to check if the provided interpolation points are valid

---

.github/workflows/tests.yml
cmake/DDCConfig.cmake.in

The call to `cmake_minimum_required(VERSION 3.3)` inside `hip-config.cmake` along with `include(CMakeFindDependencyMacro)` redefines the macro `find_dependency` with a behavior following the `OLD` policy `CMP0074`.
The trick in the PR is to redefine the macro each time we plan to use it. It slightly improve the situation.

Improve cmake workaround for rocm <6

---

examples/heat_equation.cpp
examples/non_uniform_heat_equation.cpp
examples/uniform_heat_equation.cpp
include/ddc/parallel_deepcopy.hpp

The PR makes the `parallel_deepcopy` safer with two more checks:
- ensure the dimensions of the supports have the same order (to be able to call `.kokkos_view()`)
- ensure the supports start on the same `DiscreteElement`

Make `parallel_deepcopy` safer

---

include/ddc/ddc_to_kokkos_execution_policy.hpp
include/ddc/detail/kokkos.hpp
include/ddc/parallel_for_each.hpp
include/ddc/parallel_transform_reduce.hpp

Reasons:
- not used
- std algorithms of Kokkos always annotate KOKKOS_FUNCTION the functors

Remove use_annotated_operator

---

CMakeLists.txt
README.md
cmake/DDCConfig.cmake.in

- Add version of dependencies in the README.md and in the cmake files
- update submodule googletest to v1.15.2
- update submodule benchmark to v1.9.1

Update and clarify dependencies

---

tests/splines/batched_2d_spline_builder.cpp
tests/splines/batched_spline_builder.cpp
tests/splines/extrapolation_rule.cpp
tests/splines/periodicity_spline_builder.cpp

Remove the evaluation of coordinates in batch dimensions. The reason is that these dimensions don't need to be samplings, the related coordinates are actually ignored in the evaluator.
The batch dimensions are replaced by dummy dimensions that don't need to be initialised.

Compute coordinates only on dimensions of interest

---

tests/splines/batched_2d_spline_builder.cpp
tests/splines/batched_spline_builder.cpp
tests/splines/extrapolation_rule.cpp

- template tests by discrete dimensions instead of continuous dimensions
- remove `DDim` and `BatchDims` alias templates

Template tests by discrete dimensions instead of continuous dimensions

---

.github/workflows/tests.yml
.typos.toml
AUTHORS
benchmarks/splines.cpp
docs/first_steps.md
docs/going_further.md
examples/characteristics_advection.cpp
include/ddc/detail/type_seq.hpp
include/ddc/discrete_domain.hpp
include/ddc/kernels/splines/bsplines_non_uniform.hpp
include/ddc/kernels/splines/bsplines_uniform.hpp
include/ddc/kernels/splines/spline_builder.hpp
include/ddc/kernels/splines/splines_linear_problem.hpp
include/ddc/kernels/splines/splines_linear_problem_2x2_blocks.hpp
include/ddc/kernels/splines/splines_linear_problem_maker.hpp
include/ddc/kernels/splines/splines_linear_problem_sparse.hpp
tests/splines/batched_2d_spline_builder.cpp
tests/splines/batched_spline_builder.cpp
tests/splines/extrapolation_rule.cpp
tests/splines/periodicity_spline_builder.cpp

- exclude "iy" that was fixed by "it"
- exclude "ND" related to words like "ViewND", that was fixed by "AND"
- rename "benchs" by "benchmarks"
- replace "derived" by "differentiated"

Add an automatic spell checker

---

include/ddc/chunk.hpp
include/ddc/chunk_common.hpp
include/ddc/chunk_span.hpp
include/ddc/ddc.hpp
include/ddc/ddc_to_kokkos_execution_policy.hpp
include/ddc/discrete_domain.hpp
include/ddc/for_each.hpp
include/ddc/parallel_for_each.hpp
include/ddc/parallel_transform_reduce.hpp
include/ddc/storage_discrete_domain.hpp
include/ddc/strided_discrete_domain.hpp
include/ddc/transform_reduce.hpp
tests/CMakeLists.txt
tests/chunk.cpp
tests/discrete_domain.cpp
tests/parallel_for_each.cpp
tests/storage_discrete_domain.cpp
tests/strided_discrete_domain.cpp

PoC for #438 
Steps:
Not clear if we should define an equivalent of the slice operator taking a `DiscreteDomain`
cc @science-enthusiast

Generalized domains

---

.github/workflows/tests-macos.yml
.github/workflows/tests-ubuntu.yml
benchmarks/splines.cpp

A few remarks:
- compared to the linux CI, it does not use docker images (too complicated for me to generate them correctly)
- some dependencies are installed by brew: lapack, fftw, google benchmark and google test. The other dependencies are manually compiled
- lapack is detected using pkg-config, lapacke needed to be manually specified using `LAPACKE_DIR`
- I added a temporary patch to remove `<link.h>` in the user-code plugin as suggested by the PDI team
- I temporarily disabled compilation in C++20/23 modes due to a minor bug in PDI core. The bug has been reported.

Test macOS CI

---

AUTHORS
benchmarks/splines.cpp
examples/characteristics_advection.cpp
include/ddc/kernels/splines/spline_builder.hpp
include/ddc/kernels/splines/spline_builder_2d.hpp
include/ddc/kernels/splines/spline_evaluator.hpp
include/ddc/kernels/splines/spline_evaluator_2d.hpp
tests/splines/CMakeLists.txt
tests/splines/batched_2d_spline_builder.cpp
tests/splines/batched_spline_builder.cpp
tests/splines/extrapolation_rule.cpp
tests/splines/multiple_batch_domain_2d_spline_builder.cpp
tests/splines/multiple_batch_domain_spline_builder.cpp
tests/splines/non_periodic_spline_builder.cpp
tests/splines/periodic_spline_builder.cpp
tests/splines/periodicity_spline_builder.cpp
tests/splines/spline_builder.cpp

This PR addresses #668
The batch dimensions are removed from the class templates of `SplineBuilder`, `SplineBuilder2D`, `SplineEvaluator` and `SplineEvaluator2D`, the `operator()`, relevant type aliases and methods are templated on the batched interpolation/evaluation domain instead. Some methods of the `SplineBuilder` classes now need the batched interpolation domain to be passed as argument.

Remove the batch dimensions from the SplineBuilder and SplineEvaluator class templates

---

.clang-format
.clang-tidy
.gersemirc
.github/dependabot.yml
.github/workflows/cmake-checks.yml
.github/workflows/early_integration.yml
.github/workflows/general-checks.yml
.github/workflows/gyselalibxx.yml
.github/workflows/markdown-checks.yml
.github/workflows/pages.yml
.github/workflows/python-checks.yml
.github/workflows/tests-macos.yml
.github/workflows/tests-ubuntu.yml
.github/workflows/yaml-checks.yml
.markdownlint-cli2.yaml
.pylintrc
.yamllint.yml
COPYRIGHT.md
bin/trailing_spaces
docs/CMakeLists.txt

Split and introduce dedicated workflows per language/category:
- CMake
- General
- Markdown
- Python
- YAML
Each workflow is triggered using filters.
Note that for Python `pylint` is not called on `benchmarks/splines_plot.py`, this should be fixed in the future.

Refactor workflows

---

include/ddc/ddc.hpp
include/ddc/sparse_discrete_domain.hpp
tests/CMakeLists.txt
tests/sparse_discrete_domain.cpp

This PR renames `StorageDiscreteDomain` to `SparseDiscreteDomain`, no deprecation as it is not used by downstream applications.

Rename storage to sparse

---

include/ddc/discrete_domain.hpp
include/ddc/discrete_element.hpp
include/ddc/discrete_vector.hpp
include/ddc/experimental/single_discretization.hpp
include/ddc/kernels/splines/bsplines_non_uniform.hpp
include/ddc/kernels/splines/bsplines_uniform.hpp
include/ddc/non_uniform_point_sampling.hpp
include/ddc/periodic_sampling.hpp
include/ddc/strided_discrete_domain.hpp
include/ddc/trivial_space.hpp
include/ddc/uniform_point_sampling.hpp
tests/chunk.cpp
tests/chunk_span.cpp
tests/create_mirror.cpp
tests/discrete_domain.cpp
tests/fft/fft.cpp
tests/for_each.cpp
tests/parallel_deepcopy.cpp
tests/parallel_fill.cpp
tests/parallel_for_each.cpp
tests/parallel_transform_reduce.cpp
tests/pdi/pdi.cpp
tests/relocatable_device_code.cpp
tests/single_discretization.cpp
tests/sparse_discrete_domain.cpp
tests/strided_discrete_domain.cpp
tests/transform_reduce.cpp

- Remove some `uid`
- Replace calls to `DiscreteElement` constructor with integer
Some are remaining in the splines builder and evaluator. The `DiscreteElement` tests also rely on it, not sure this is needed.

Remove direct calls to integer constructor of DiscreteElement

---

.github/workflows/cmake-checks.yaml
.github/workflows/early_integration.yaml
.github/workflows/general-checks.yaml
.github/workflows/gyselalibxx.yaml
.github/workflows/markdown-checks.yaml
.github/workflows/packages-cleanup.yaml
.github/workflows/pages.yaml
.github/workflows/python-checks.yaml
.github/workflows/shell-checks.yaml
.github/workflows/tests-macos.yaml
.github/workflows/tests-ubuntu.yaml
.github/workflows/tests-windows.yaml
.github/workflows/website-checks.yaml
.github/workflows/yaml-checks.yaml

This PR aims to harden security following [github recommendations](https://docs.github.com/en/actions/security-for-github-actions/security-guides/security-hardening-for-github-actions#using-third-party-actions)
>Pin actions to a full length commit SHA
Note that as a consequence, this will increase the number of dependabot PRs.

Set commit sha instead of version of github actions

---

include/ddc/kernels/splines/kokkos-kernels-ext/KokkosBatched_Gbtrs_Serial_Impl.hpp
include/ddc/kernels/splines/splines_linear_problem_sparse.hpp

I made a quick review, I think we don't have dangerous calls to `stride(i)`. We don't have functions that allow multiple ranks.

Prefer stride(i) instead of stride_i()

---

.github/workflows/tests-ubuntu.yaml

The C `assert` clauses are not well suited for coverage. They will always at most partial coverage.

Do coverage test in NDEBUG

---

include/ddc/kernels/splines.hpp
include/ddc/kernels/splines/spline_traits.hpp
tests/splines/CMakeLists.txt
tests/splines/spline_traits.cpp

This PR aims at a helper to check the consistency of spline builder and evaluator.
For some reason, I need double parentheses to use `ASSERT_FALSE` like 
`ASSERT_FALSE((ddc::is_spline_compatible_v<Builder2D_1, Builder2D_1>));`

Add spline compatibility check helper

---

.github/workflows/tests-macos.yaml

The image macos-latest is about to change definition. Let us be explicit about the tested version.
This leads to disable C++23 build as recent versions of libc++ implement `std::mdspan` and Kokkos does not handle it correctly.

Explicit use of macos-15

---

.github/workflows/tests-macos.yaml
.github/workflows/tests-windows.yaml

Fixed by https://github.com/kokkos/kokkos/pull/8234 available in Kokkos 4.7

Add C++23 Windows and macOS builds
